### ISSUE TITLE
Question: Any plans on supporting AWS SSO?

### ISSUE THREAD

**Issue by efrench-novi** [trek10inc/awsume#102]

**Comment by kirnberger1980** [comment]
As we are planning to migrate our user pool in our user account to AWS SSO and awsume is our fav tool, we would like to have support for AWS SSO. Any plan on this?

**Comment by mbarneyjr** [comment]
Hi! Sorry for the delayed response! I'm working on an update now that will support the `credential_process` [profile setting](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html), which can be used in combination with [this](https://github.com/benkehoe/aws-sso-credential-process) to provide AWS SSO support.

Beyond that, we'll be looking into incorporating that package for native AWS SSO support in awsume

**Comment by mbarneyjr** [comment]
Closing in favor of #101
