### ISSUE TITLE
Remove support for AWS_SECURITY_TOKEN

### ISSUE THREAD

**Issue by mgmarino** [trek10inc/awsume#105]
First off, great little tool, we are very happy to use it.

This issue is to consider dropping support for `AWS_SECURITY_TOKEN`.  AWS switched over its usage [6 years ago](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/) and most documentation only references `AWS_SESSION_TOKEN` now.  By retaining it, I believe it can only create confusion.  Indeed, in our case if created some hard to track down issues when: the standard environment variables were updated and we forgot to update AWS_SECURITY_TOKEN env var as well.  

My proposal would be the following:

- Remove default export of `AWS_SECURITY_TOKEN`, but perhaps allow it to be exported if a configuration is set.

I'm happy to open a PR, but would like to get any comments/concerns first.

**Comment by mbarneyjr** [comment]
Hi, sorry for the delay in response! I've implemented this and a few other fixes. This should be found in pre release 4.5.0a1. I'll deploy this to release 4.5.0 once I'm confident in the changes. If you experience any issues with pre release 4.5.0a1 please update this issue, thanks!

**Comment by mgmarino** [comment]
Thanks, I have been using the 4.5.0a3 and haven't seen any issues.

**Comment by mgmarino** [comment]
@mbarneyjr  Thanks for this!  Any idea when you might push a release?

**Comment by mbarneyjr** [comment]
Sorry for the delay, deployed to 4.5.0!
