### ISSUE TITLE
bug when using -o flag?

### ISSUE THREAD

**Issue by blastik** [trek10inc/awsume#106]
Hi folks!

I'm using v4.4.1 and I've realised that now when i run `awsume whateverprofile -o whateverprofile` apart from updating the `credentials` file it also sets the environment variables.

is that expected?

thank you

**Comment by mbarneyjr** [comment]
Yep, it's expected that your environment variables get exported even when using the `-o` flag. Awsume should always export environment variables so long as it successfully retrieved credentials

**Comment by blastik** [comment]
@mbarneyjr got it but... does it make sense ? i run -o because i want them only in `credentials` so i can then switch between the profiles.
