### ISSUE TITLE
 The environment variables weren't being set properly when running awsume.

### ISSUE THREAD

**Issue by ahadcse** [trek10inc/awsume#108]
Hi,
I am trying to use awsume to assume a role, but it doesn't switch role when I input awsume <role_name>.
As a workaround, I have to input awsume <role_name> -s and then paste the output again. 

N.B: I am using Macbook Pro. I have configured my .bash_profile with alias:  alias awsume='. awsume' 

Can you please help me on what am I doing wrong?

**Comment by bugwrangler** [comment]
I had been facing same issue too, using similar workaround. 

awsume --unset also doesn't work
/usr/local/bin/awsume: line 71: return: can only `return' from a function or sourced script

**Comment by mbarneyjr** [comment]
This problem usually occurs due to the alias not being set in your active shell. If you run the `alias` command, do you see the correct awsume alias displayed?

**Comment by bugwrangler** [comment]
yep! thanks! worked after adding the alias in zsh :) 

alias awsume=". awsume"

**Comment by mbarneyjr** [comment]
@ahadcse have you resolved the issue?

**Comment by mbarneyjr** [comment]
Closing, but if you're still experiencing issues feel free to re-open

**Comment by ahadcse** [comment]
@mbarneyjr When I run alias command I cannot see anything regarding awsume even though I have the line 
**alias awsume=". awsume"**
in my .bash_profile file. I guess I was not able to set alias and the problem is not solved yet

**Comment by ahadcse** [comment]
@mbarneyjr Oh I have not given the command $source .bash_profile. Now it works. Thanks for helping

**Comment by mbarneyjr** [comment]
It might be that your shell is zsh, so it won't load your `~/.bash_profile` on login. The zsh equivalent file is generally `~/.zshenv`
