### ISSUE TITLE
Support credential_process to obtain credentials

### ISSUE THREAD

**Issue by v-mendez** [trek10inc/awsume#109]
Integrate [credential_process](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sourcing-external.html) to obtain credentials from an external process.

**Comment by mbarneyjr** [comment]
Hi, thanks again for the PR! I've merged it and implemented a few other fixes. This should be found in pre release 4.5.0a1. I'll deploy this to release 4.5.0 once I'm confident in the changes. If you experience any issues with pre release 4.5.0a1 please update this issue, thanks!

**Comment by mbarneyjr** [comment]
Sorry for the delay, this has been deployed to 4.5.0
