### ISSUE TITLE
The config profile (autoawsume-[profile-name]) could not be found

### ISSUE THREAD

**Issue by tero** [trek10inc/awsume#119]
I tried to use aws-cli when the session token was expired and got `The config profile could not be found` error. Ok, I restart awesume, I thought. But running awsume now fails with same error. Only way to fix this was to switch new terminal window.

**Comment by mbarneyjr** [comment]
Hi, thanks for the bug report! I've implemented a fix and it should be found in pre release 4.5.0a1. I'll deploy this to release 4.5.0 once I'm confident in the changes. If you experience any issues with pre release 4.5.0a1 please update this issue, thanks!

**Comment by tero** [comment]
Great, thanks! I'll just upgraded to pre-release and will update if there will be any issues with it.

**Comment by tero** [comment]
I think this broke MFA support? Pre-release version doesn't ask for MFA token but shows and error: `Awsume error: An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:iam::[account]:user/[user] is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::[another-account]:role/AdminAccessFromLoginRole`

**Comment by mbarneyjr** [comment]
4.5.0 has been released
