### ISSUE TITLE
Awsume /Awsumepy for IAM role is not working properly ! 

### ISSUE THREAD

**Issue by aharrim** [trek10inc/awsume#12]
Hey guys, 
I'm not sure where to send the issue but On June , I downloaded your"awsume" utility so I will be able to assume an IAM role easily through CMD and it was working fine . 
Recently , I got a new machine and I downloaded your tools  but it seems it's not working anymore .
My new machine is windows 10 and I believe that you guys updated the utility so I'm not sure if I'm missing something or there's something wrong .

I created same profiles I had on my old machine and i was trying to assume one of them through the following command  ..:
awsume AEProfile 
After that , it asks me for mfa code which I enter but then it seems like it just keep assume the source profile and not the role (Plus I noticed that after i entered mfa code , there are two sentences showed which are "User profile credentials will expire " and "Role Profile credentials will expire" .

The thing is the expiration date/time for the role is the same date/ time i ran the command at , Please  find the attachment .

Then to verify which profile is being used , i ran the following command ..:
aws sts get-caller-identity but it keep giving me the source profile and not the role !

Regards,
Ahmad
![capture](https://user-images.githubusercontent.com/12396227/30079017-cc6fb2bc-924c-11e7-8ec0-c6583f78ba58.PNG)

**Comment by shortjared** [comment]
We'll take a look! cc: @mbarneyjr

**Comment by mbarneyjr** [comment]
`awsume` is the shell wrapper to `awsumepy`.

`awsumepy` just prints the credentials that the shell wrapper `awsume` will use to set environment variables.

So, to use Awsume on any given profile, in your case `AEProfile`, run `awsume AEProfile`. It appears that you were running it with `awsumepy` instead of `awsume`. If running `awsume` still doesn't resolve the issue let me know!

**Comment by vpuech** [comment]
hi, Same problem with awsume. 
if i do a awsume MyProfile -s and copy/paste the exports it works but not with awsume MyProfile directly

**Comment by mbarneyjr** [comment]
@vpuech Can you provide more details? What OS are you using? Did you install normally with pip? What version of python are you using? Please include any additional details

**Comment by aharrim** [comment]
@mbarneyjr  It's same with "awsume" but the screenshot showed "awsumepy"
Please, find the attachment 
![capture](https://user-images.githubusercontent.com/12396227/30112630-0987ae78-92e0-11e7-974d-2c7c37e7f0e6.PNG)


Regards,

**Comment by mbarneyjr** [comment]
Are you using the most current version of Awsume? You can run `awsume -v`. The current version is 1.2.4. If you're using the current version of Awsume and are still experiencing problems, run `awsume --info` and post the output

**Comment by aharrim** [comment]
@mbarneyjr  It's latest version (1.2.4) . I believe the older version , which i was using 2 months ago was working fine but this one is not .
Anyway , find the attachment .
![capture](https://user-images.githubusercontent.com/12396227/30125709-5188188a-9307-11e7-9a8f-33bd5cf37a4a.PNG)


 I believe  there's a problem in your newer version of the tool because I've been able to assume IAM role profile using "set aws_profile" , Please find the second attachment. 
![capturesetprofile](https://user-images.githubusercontent.com/12396227/30125859-e1097dfa-9307-11e7-84a8-e347cf72a9b0.PNG)

Thanks,

**Comment by mbarneyjr** [comment]
Run Awsume with the `--info` flag for the profile you want to awsume. For instance, if you want to awsume `AEProfile`, run `awsume AEProfile --info` and post the output of that.

Running `set aws_profile=AEProfile` only sets that environment variable, so when you run commands like `aws get-caller-identity`, the awscli looks to that profile, located in your `~/.aws/config` and `~/.aws/credentials` files, for which credentials to use.

**Comment by aharrim** [comment]
@mbarneyjr  Here's the output 
![capture](https://user-images.githubusercontent.com/12396227/30126808-2f8ba0ea-930b-11e7-946c-41eeb6f234fc.PNG)

**Comment by mbarneyjr** [comment]
Alright, I found the problem, and have released an update that should fix any issues you were having. The current version is 1.2.5. If you are still experiencing problems please let me know!

@vpuech Are you still experiencing issues? If so, I'd be happy to help you resolve them.

**Comment by aharrim** [comment]
Cool , I uninstall and install the newer version and now it's working fine .
Thanks for your time and effort !

**Comment by mbarneyjr** [comment]
No problem! I'm happy everything is working well now!
