### ISSUE TITLE
awsume not exporting secrets to env vars

### ISSUE THREAD

**Issue by alexM0** [trek10inc/awsume#122]
Hi,

For some reason awsume is not exporting secrets to environment variables automatically.
I have tried uninstall and installing a fresh copy and it still had the same issue.

I have to run:

`awsume <profile_name> -s `

Copy and paste the output for all the exports, and then continue on my way.

Is there a reason why awsume would not be exporting these automatically? Is there something I can configure for this to work?

Thanks

**Comment by ryansb** [comment]
If you don't have `alias awsume=". awsume"` set for your shell this will stop environment variables from being exported.

**Comment by alexM0** [comment]
Thanks, that fixed it.
