### ISSUE TITLE
Add argument to add tags to STS session

### ISSUE THREAD

**Issue by lpearson-trek10** [trek10inc/awsume#128]
Something similar to what you would do if you were adding tags when calling `aws sts assume-role`

`--tags Key=mykey,Value=myvalue Key=mykey2,Value=myvalue2`

**Comment by ryansb** [comment]
It would be nice to support a kwarg-style `key=value` to make it easy to do interactively for simple alphanumeric pairs. The verbose Key=mykey,Value= should only be for cases where you've got odd spacing or quoting.

**Comment by pbinczyk** [comment]
I've also noted the need to tag STS sessions.
Just prepared a ready PR with this solution: https://github.com/trek10inc/awsume/pull/216

It would be great to see it merged ;)

**Comment by mtskillman** [comment]
closed by https://github.com/trek10inc/awsume/pull/225
