### ISSUE TITLE
Support Yubikey 2FA

### ISSUE THREAD

**Issue by aleksandersumowski** [trek10inc/awsume#130]
From docs: `Note: Only virtual MFA devices are supported by awsume at this time.` 

Any chance of supporting yubikeys as well?

**Comment by wesleykirklandsg** [comment]
Adding to this. I have a Yubikey for my job and we have many client AWS accounts all with different auth profiles.

**Comment by mtskillman** [comment]
need to update plugin documentation to mentoion https://github.com/kylejwatson/awsume-yubi-plugin

**Comment by xeger** [comment]
YubiKey and 1Password are now supported via plugins; see the docs that @mtskillman mentioned.
