### ISSUE TITLE
awsume in shell scripts

### ISSUE THREAD

**Issue by Nemunas** [trek10inc/awsume#155]
I'm trying to run awsume in a shell script but getting an error:

```
#!/bin/bash

awsume [ role ] --refresh
```

`
/home/me/.local/bin/awsume: line 181: return: can only 'return' from a function or sourced script
`

**Comment by mbarneyjr** [comment]
The awsume shell script expects to be sourced. An alias should be loaded into your login file automatically when awsume itself is installed, but that can fail. Running `awsume-configure` should try to set awsume up for all installed shells after installation

We'll see how we can add a warning to the shell script if it's not being sourced to help make this a little more clear. If you still have any issues after setting up the alias and reloading your terminal, feel free to re open this issue or create a new one!

**Comment by adnan-asad01** [comment]
Why doesn't `awsume-configure` add the alias to `.zshrc` as well? @mbarneyjr

**Comment by stuertz** [comment]
solution from #163 is to use `source`
```
#!/bin/bash

source awsume [ role ] --refresh
 ```
