### ISSUE TITLE
awsume is not recongnized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by devineni25** [trek10inc/awsume#165]
When I type awsume command, it's give me the error attached in the screen shot. 

I'm unable to find what the issue is.

![awsume error](https://user-images.githubusercontent.com/24370879/134947863-6a61b8fc-acd1-4ed6-90e4-5d4e8062d871.PNG)

**Comment by mtskillman** [comment]
@devineni25 please provide more information on what method/approach you used to install awsume. (apologies for the ~2 years delay here)
