### ISSUE TITLE
Installation Error: Error 1

### ISSUE THREAD

**Issue by sysadminAbtrace** [trek10inc/awsume#167]
Hello, 

Trying to install awsume on a AWS Workspace and I am getting the following error: 

ERROR: Command errored out with exit status 1: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'D:\\Users\\theodore\\AppData\\Local\\Temp\\pip-install-785h_jja\\psutil_0bcd3e15f877442fa8a829e633d5b0cc\\setup.py'"'"'; __file__='"'"'D:\\Users\\theodore\\AppData\\Local\\Temp\\pip-install-785h_jja\\psutil_0bcd3e15f877442fa8a829e633d5b0cc\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'D:\Users\theodore\AppData\Local\Temp\pip-record-qtfwl318\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\psutil' Check the logs for full command output.

What am I missing here?

**Comment by mtskillman** [comment]
@sysadminAbtrace please provide more information on what method you are using to install awsume. (apologies for the ~2 years delay here)

**Comment by sysadminAbtrace** [comment]
It would have been pip. But this is ancient now, I have since then changed machines and can't reproduce the bug.
