### ISSUE TITLE
awsume -l (account listing) improvements

### ISSUE THREAD

**Issue by shortjared** [trek10inc/awsume#18]
`awsume -l` goes to stderr, which is a little annoying when I want to grep. It forces the command to be `awsume -l 2>&1 | grep acct-name`.

Also, any chance we could get account numbers added to the listing?

**Comment by mbarneyjr** [comment]
Improvements included in the release 2.1.2, thanks!

**Comment by shortjared** [comment]
Thank YOU!

![clapping](https://giphy.com/gifs/people-imgur-QWrClN3mlYtHO?tc=1)
