### ISSUE TITLE
Getting error even after awsume-configure

### ISSUE THREAD

**Issue by saravanastar** [trek10inc/awsume#188]
Getting the below error when I run the command **awsume profile-name**

I ran awsume-configure multiple time but still throwing the same error.

**Warning: the awsume shell script is not being sourced, please use awsume-configure to install the alias
/opt/homebrew/bin/awsume: line 183: return: can only `return' from a function or sourced script**

**Comment by mtskillman** [comment]
@saravanastar would you confirm that your awsume alias is set correctly? there should be something like this in your .profile (or equivalent file for whichever shell your are using, if it is not bash) 
```
#AWSume alias to source the AWSume script
alias awsume="source awsume"
```


try this:
`alias | grep awsume`

should output
`alias awsume='source awsume'`

**Comment by uavail** [comment]
It works. Thanks for checking. We can close this

**Comment by saravanastar** [comment]
It works. Thanks for checking
