### ISSUE TITLE
AWSUME --auto-refresh not working

### ISSUE THREAD

**Issue by e3kbobro** [trek10inc/awsume#190]
![image](https://user-images.githubusercontent.com/94838661/180406124-bfa5d69c-bd12-460a-b36f-dfd9dc242047.png)
I have an issue with the awsume command --auto-refresh
Is it because I'm logged in with a federated account and not authorized to view Account? Or is it something else that I'm missing?

**Comment by mtskillman** [comment]
@e3kbobro apologies for long delay here but basically 
`awsume --auto-refresh`
will attempt to auto-awsume your "default" profile in your ~/.aws/config

in contrast, try doing 
`awsume --auto-refresh <<desired_profile_name_here>>
`
such as 
`awsume --auto-refresh my-company-prod`
