### ISSUE TITLE
Error: "Awsume error: credential_process error: ERROR: string indices must be integers"

### ISSUE THREAD

**Issue by manu-remsense** [trek10inc/awsume#193]
Hey guys,

I'm having a massive issue here, which I can't for the life of me figure out.

I'm using WSL v2, Ubuntu 20.04.5, python 3.8.10, pipx 1.1.0, aws-sso-util 4.28.0, awsume 4.5.3 and aws cli is "aws-cli/2.7.29 Python/3.9.11 Linux/5.10.16.3-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off"

I log in successfully with aws-sso-util but.. when I try to awsume a role, it gives me this error.
`Awsume error: credential_process error: ERROR: string indices must be integers`

I have an exact copy of a file from a computer where it works, so it's not the config syntax issue.

Python, awsume, aws-sso-util, pipx, are all the same on the pc that it works and pc where it doesn't.

I'm really lost here, any ideas? Any help would be appreciated.

**Comment by timohirt** [comment]
See #191

**Comment by mtskillman** [comment]
fixed in aws-sso-util v4.29 
see https://github.com/benkehoe/aws-sso-util/issues/70 for context

**Comment by manu-remsense** [comment]
> fixed in aws-sso-util v4.29 see [benkehoe/aws-sso-util#70](https://github.com/benkehoe/aws-sso-util/issues/70) for context

Indeed, it was eventually fixed, thanks!
