### ISSUE TITLE
Bug: Account Id shows incorrectly if not the "aws" partition

### ISSUE THREAD

**Issue by LucasZielke** [trek10inc/awsume#194]
When `--list-profiles` is run and users/roles for alternate aws partitions (such as `aws-us-gov` and `aws-cn`) the listed account id shows just the word "arn".

![word arn showing when listing account](https://user-images.githubusercontent.com/13828175/189544014-8f32e9f3-e55e-4ef4-a806-cb3acfba7588.png)

most likely due to manually removing part of the user/role arn on:
https://github.com/trek10inc/awsume/blob/efec1b0c063bedce081f7a89da16bc29fd40e166/awsume/awsumepy/lib/profile.py#L269-L271

**Comment by mtskillman** [comment]
resolved by https://github.com/trek10inc/awsume/pull/226
