### ISSUE TITLE
Unset variable feature

### ISSUE THREAD

**Issue by holybit** [trek10inc/awsume#21]
A common issue I have is I need to unset all existing shell environment variables that a previous run of `. awsume -s PROFILE` set.

Woud be nice if you could run `awsume -u` and it would dump something such as:

```bash
$ awsume -u
unset AWS_SECRET_ACCESS_KEY
unset AWS_ACCESS_KEY_ID
etc...
```

**Comment by mbarneyjr** [comment]
If you execute `awsume -k`, which normally is used to stop awsume role auto-refresher, it will unset all environment variables that awsume sets.

This feature hasn't been documented, but I will be sure to document it in the usage description in the next release.

**Comment by holybit** [comment]
I would like to request this issue be re-opened @mbarneyjr.

First, the docs still don't say that `awsume -k` will unset all env vars. Secondly, it's not good CLI arg form to have a single command do two things at once. I would say add a `-u` flag for unset.

```sh
$ awsume -v
3.2.5
$ awsume -h
...
  -k, --kill-refreshing                       Kill autoawsume
...
```

**Comment by mbarneyjr** [comment]
AWSume 3.2.8 is released and now includes a dedicated "environment variable unset" feature; check out the [changelog](https://github.com/trek10inc/awsume/wiki/Changelog#328---2018-4-30---bug-fixes) for more details on this update

Thanks for the request!
