### ISSUE TITLE
Awsume error: Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed: b''

### ISSUE THREAD

**Issue by rustyshackleford96** [trek10inc/awsume#212]
Hi, hope you're well

I'm struggling to get awsume running on my WSL Ubuntu and get the following error `Awsume error: Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed:
b''`

I have set up aws config and credentials files correctly, when I 'awsume' to the relevant AWS account I get the above error.
Are you able to assist at all?

**Comment by mtskillman** [comment]
@AadilDokrat hi would you provide further details such as which awsume command you are running as well as which version of awsume you are using?
