### ISSUE TITLE
[Feature request] Show current/active profile

### ISSUE THREAD

**Issue by calebplum** [trek10inc/awsume#235]
When I'm working in multiple AWS accounts concurrently I sometimes forget which profile I've assumed in a given terminal session. Usually I'll run something like `aws s3 ls` and try to use the output to figure out which account I'm in, but it'd be useful if awsume had a built-in feature to indicate the active profile.

This could either be implemented as a separate command-line flag where the name of the current profile is printed, or it could be included in the output of the existing `-l`/`--list-profiles` flag, where the currently-assumed profile is marked with a symbol next to it.

**Comment by mtskillman** [comment]
addressed by PR 243
