### ISSUE TITLE
Version 4.5.4 did not ship to PyPi

### ISSUE THREAD

**Issue by jimsmith** [trek10inc/awsume#245]
Hi, as #220 is closed off and I left a few comments in there, when will this version be shipped to PyPi as your pipeline failed to publish due to two factor auth enabled at PyPi which your pipeline publishing to PyPi doesn't publish.

https://github.com/trek10inc/awsume/issues/220#issuecomment-1855723787

I did tag in https://github.com/lhendrick-t10 on the above issue but there was never an acknowlegement so tagging in other users that this issue allows me to tag in.
@jaykay @xeger @robinro @jthomerson @valdisrigdon

**Comment by mtskillman** [comment]
@jimsmith acknowledged -- we are working to correct this issue

**Comment by lhendrick-t10** [comment]
@jimsmith - This is resolved and 4.5.4 has been published to PyPi, thank you for raising this issue and your continued support of awume!

**Comment by chenrui333** [comment]
@lhendrick-t10 seeing 4.5.5 release missing on pypi, raised a separate issue on it, https://github.com/trek10inc/awsume/issues/289
