### ISSUE TITLE
should check mfa_serial from source profile

### ISSUE THREAD

**Issue by pschulten** [trek10inc/awsume#26]
I would be convenient if awsume would also read the source profile in order to get the mfa_serial so we could define it once for and account in the source profile. 
Currently we have to duplicate the serial in many [profile] sections

**Comment by mbarneyjr** [comment]
@pschulten I apologize for getting back to you so late, but this functionality is now supported in AWSume release 3.0.0, thanks for the tip!

**Comment by pschulten** [comment]
@mbarneyjr no need to apologize! Thanks a lot.
