### ISSUE TITLE
awsume -a should also set AWS_DEFAULT_REGION and AWS_REGION

### ISSUE THREAD

**Issue by felipe1982** [trek10inc/awsume#28]
awsume -a only sets AWS_PROFILE and AWS_DEFAULT_PROFILE. I think it should also set region, if the role has the region set, else use the region in `default` has the region set.

**Comment by felipe1982** [comment]
Might relate to issue #15

**Comment by mbarneyjr** [comment]
This has been resolved in version 3.0.9

Thanks for the tip!
