### ISSUE TITLE
Provide a way to display current role in command prompt

### ISSUE THREAD

**Issue by jangroth** [trek10inc/awsume#31]
Awesome piece of software, loving it!

It would be great if there was a way to query awsume for the current profile, so that this information could be used elsewhere (e.g. to display the current role in the shell command prompt).

Or is this already possible and I'm missing it from the documentation?

**Comment by mbarneyjr** [comment]
When you awsume a profile, the name of that profile is exported to the `AWSUME_PROFILE` environment variable.

So if you were to run `awsume client-dev`, the value of that environment variable would be "client-dev", if the command executed successfully.

This isn't explicitly defined in the documentation, but I will be sure to add it in the wiki!

We're glad you're enjoying it, if you have any other tips or suggestions we're always open to feedback!

**Comment by jangroth** [comment]
Thanks, that's great!
