### ISSUE TITLE
LIGHTCYAN doesn't seem to exist

### ISSUE THREAD

**Issue by gcohler** [trek10inc/awsume#35]
Hi,  I had trouble recently with the fact that Fore.LIGHTCYAN_EX didn't exist.  Perhaps you could pick another color.  I'm not sure where it went.  I just substituted BLUE, and everything worked fine.

**Comment by mbarneyjr** [comment]
Thanks for the bug report!

What is the environment you're working in? Are you using the most up-to-date version of `colorama`?
It's weird that it doesn't exist for you.

**Comment by mbarneyjr** [comment]
What version of `colorama` does your machine have installed? Can you post the output from `pip freeze`?

**Comment by gcohler** [comment]
Here's the output from pip freeze (and pip3 freeze output is below too):

Cheetah==2.4.4
Landscape-Client==14.12
PAM==0.4.2
PyYAML==3.10
SecretStorage==2.0.0
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
apt-xapian-index==0.45
argparse==1.2.1
awsume==3.2.8
boto3==1.7.29
chardet==2.0.1
cloud-init==0.7.5
colorama==0.2.5
configobj==4.7.2
html5lib==0.999
httplib2==0.8
jsonpatch==1.3
jsonpointer==1.0
keyring==3.5
launchpadlib==1.10.2
lazr.restfulclient==0.13.3
lazr.uri==1.0.3
oauth==1.0.1
prettytable==0.7.2
pyOpenSSL==0.13
pycrypto==2.6.1
pycurl==7.19.3
pygobject==3.12.0
pyserial==2.6
python-apt==0.9.3.5ubuntu2
python-debian==0.1.21-nmu2ubuntu2
requests==2.2.1
simplejson==3.3.1
six==1.5.2
ssh-import-id==3.21
urllib3==1.7.1
wadllib==1.3.2
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5

And here's the output from pip3 freeze:

Yapsy==1.11.223
awsume==3.2.3
boto3==1.7.25
botocore==1.10.25
chardet==2.2.1
colorama==0.2.5
command-not-found==0.3
docutils==0.14
future==0.16.0
html5lib==0.999
jmespath==0.9.3
language-selector==0.1
psutil==5.4.5
pycurl==7.19.3
pygobject==3.12.0
python-apt==0.9.3.5ubuntu2
python-dateutil==2.7.3
requests==2.2.1
s3transfer==0.1.13
six==1.5.2
ufw==0.34-rc-0ubuntu2
unattended-upgrades==0.1
urllib3==1.7.1
wheel==0.24.0

**Comment by mbarneyjr** [comment]
It appears that your `colorama` is out of date. Can you upgrade it through `pip install --upgrade colorama` (which may require `sudo`) and let me know if that fixes the issue?

**Comment by gcohler** [comment]
Yes.  That fixed the problem.  It installed 0.3.9 over 0.2.5.  I think adding a minimum version to the dependency graph would do the trick.  Thanks very much.
