### ISSUE TITLE
awsume fails to install on linux when powershell is installed.

### ISSUE THREAD

**Issue by jkrukoff-cb** [trek10inc/awsume#45]
When attempting to install awsume on Ubuntu 18.10 with powershell installed, the pip install command hangs while installing the awsume package. No output is shown, and the pip command has to be killed manually (Ctrl+C & Ctrl+Z are even captured and ineffective!). Without powershell installed, things work fine.

It'd be nice if there was a way to disable the shell profile hooks during install, perhaps by environment variable. I have to manually remove them every time, since they conflict with my own shell setup that manages awsume differently.

**Comment by mbarneyjr** [comment]
Hi @jkrukoff-cb ,
In the next release of awsume, there will be a way to disable the extra setup post-install with an environment variable.

However I'll look into ways to fix the post-install setup with powershell on ubuntu. Thanks for bringing this to our attention!

**Comment by mbarneyjr** [comment]
Hey @jkrukoff-cb, awsume 4.0.0 was released today and should have fixed this bug. I'm going to close this issue. If you're still experiencing issues feel free to re open this issue or open a new one!
