### ISSUE TITLE
awsume fails to export the SessionToken value to the shell environment

### ISSUE THREAD

**Issue by paulbrice** [trek10inc/awsume#46]
I am running 'awsume' using a shared credentials file. The config file contains profiles using a source profile in the credentials file. The source profile contains both key attributes as well as a session token as its created from a federated credential. I never have credentials stored in [default].

Issue: The session token is never exported to the shell environment.

Example: config file

```
[default]
region = us-east-1

[profile internal-admin]
role_arn = arn:aws:iam::<your aws account id>:role/admin-role
source_profile = joel
region = us-east-1
```

Example: credentials file

```
[default]

[joel]
aws_access_key_id = AKIAIOSFODNN7EXAMPLE
aws_secret_access_key = wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
aws_session_token     = FQoGZXIvYXdzEK3//////////w==
```

OS: Mac High Sierra
Shell: bash / zsh

**Comment by tehmaspc** [comment]
Seeing same thing here. Same DEV environment. :(

**Comment by mewelling** [comment]
@tehmaspc Thanks so much - that got it working for me too!

**Comment by mbarneyjr** [comment]
#56 added this functionality, a new version coming soon, closing

Thanks for the feature request!
