### ISSUE TITLE
support for credential_source

### ISSUE THREAD

**Issue by sdevang** [trek10inc/awsume#60]
I see awsume does not support credential_source awscli configuration option.

It is expecting role_arn and source_profile in awscli config file or else it reports "Invalid Profile"

This parameter(credential_source) cannot be provided alongside source_profile and awsume does not like if source_profile is not configured.

More details, 
https://docs.aws.amazon.com/cli/latest/topic/config-vars.html

**Comment by mbarneyjr** [comment]
Hey @sdevang ,

Thank you for bringing this to our attention. We will be sure to resolve this issue in the next release of awsume!

**Comment by sdevang** [comment]
Do you have any ETA on next release date ? We use awsume extensively in our setup and this feature is really needed for current project.

**Comment by mbarneyjr** [comment]
We should be done with it within the next few weeks, maybe sooner

**Comment by mbarneyjr** [comment]
Hey @sdevang , we released 4.0.0 which should have resolved this issue. If you're still having problems feel free to re-open this issue or open a new one!
