### ISSUE TITLE
awsume integration with SAML

### ISSUE THREAD

**Issue by syedhamid09** [trek10inc/awsume#74]
Hi

Im looking for any documentation on how to setup awsume with SAML

Thanks
Syed

**Comment by mbarneyjr** [comment]
Hey @syedhamid09 

All documentation for awsume is hosted here: https://awsu.me/


To get credentials with SAML, you have to create a plugin that interfaces with whatever SAML provider you use and return the assertion.

General plugin development:
https://awsu.me/plugin-development/

SAML function documentation:
https://awsu.me/plugin-development/get-credentials.html#get-credentials-with-saml

We welcome any feedback for the documentation
