### ISSUE TITLE
awsume does not work after upgrading from 3.2.8 to 4.1.9

### ISSUE THREAD

**Issue by BuSchu** [trek10inc/awsume#76]
After upgrading awsume from 3.2.8 to 4.1.9 my colleague and I get an error message when calling "awsume terraform":
Awsume error: Invalid profile terraform Missing keys aws_access_key_id, aws_secret_access_key
Our configuration is standard, we think:

~/.aws/config:

[default]
region = eu-central-1
output = json

[profile terraform]
region = eu-central-1
output = json
mfa_serial = arn:aws:iam::<account nr>:mfa/scht

[profile DQCustOpsAdmin]
region = eu-central-1
output = json
role_arn = arn:aws:iam::<account nr>:role/AdminOrganization
source_profile = default
mfa_serial = arn:aws:iam::<account nr>:mfa/scht

[profile prod-admin]
region = eu-central-1
output = json
role_arn = arn:aws:iam::<account nr>:role/AdminUserRole
source_profile = terraform

[profile staging-admin]
region = eu-central-1
output = json
role_arn = arn:aws:iam::<account nr>:role/AdminUserRole
source_profile = terraform

with 2 different account numbers.

~/.aws/credentials:

[default]
aws_access_key_id = <access key>
aws_secret_access_key = <secret key>

[profile terraform]
aws_secret_access_key = <secret key>
aws_access_key_id = <access key>

with 2 different sets of keys.

~/.awsume/config.yaml:

{colors: true, fuzzy-match: false, role-duration: 0}

All this was working for months with awsume 3.2.8.

**Comment by mbarneyjr** [comment]
One of the breaking changes from 3.x to 4.x was that awsume follows the config and credentials files requirements closer to what is documented, specifically this line from the documentation:

https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

> The credentials file uses a different naming format than the CLI config file for named profiles. Include the prefix word "profile" only when configuring a named profile in the config file. Do not use the word profile when creating an entry in the credentials file.

It looks like your `~/.aws/credentials` file has a profile named `profile terraform` where it should be just `terraform`
