### ISSUE TITLE
AWS credentials Provider

### ISSUE THREAD

**Issue by HanithaKrishnaraj** [trek10inc/awsume#78]
Hi Team,

I have looked in to the asume documentation
https://awsu.me/

I need to know how to add the plugin and test in different environment

**Comment by mbarneyjr** [comment]
Hi @HanithaKrishnaraj ,

Can you elaborate on what you mean by "test in a different environment?"

If you mean assuming a  different role, you can check out the documentation on named profiles here: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html

**Comment by HanithaKrishnaraj** [comment]
Hi mbarneyjr,

I need to save my aws credentials in secured way and use inside application.

How Awsume is secured to store the credentials and how to add the plugins and fetch the credentials from java application?

**Comment by mbarneyjr** [comment]
If I understand you correctly, awsume is not what you're looking for. Awsume is an application that you use in a shell like bash/powershell, it's not something designed to be used within something like a java application. It's purpose is to help you assume roles in different accounts in the terminal, so that you can perform actions against your account.

**Comment by HanithaKrishnaraj** [comment]
My idea is to store these credentials in secured way and fetch it back.
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY

Thanks for your reply.

**Comment by mbarneyjr** [comment]
For work locally, you generally will put those credentials in your `~/.aws/credentials` file. Here is the documentation on that: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html

**Comment by mbarneyjr** [comment]
Closing this issue

If you're experiencing an issue with awsume, please feel free to open another issue!
