### ISSUE TITLE
Incomplete troubleshooting solution

### ISSUE THREAD

**Issue by MarkWoods1977** [trek10inc/awsume#82]
https://awsu.me/troubleshooting/#i-m-getting-an-installation-error-fatal-error-python-h-no-such-file-or-directory will not solve the issue if using python3. 

`yum install python3-devel ` is needed if Python3. I tested with 3.7

**Comment by mbarneyjr** [comment]
Thanks for letting us know! We pushed an update to mention Python3 and other package managers
