### ISSUE TITLE
awsume -l throws error when trying to install on Jenkins

### ISSUE THREAD

**Issue by varun1231** [trek10inc/awsume#83]
```
Traceback (most recent call last):
  File "/var/lib/jenkins/.local/bin/awsumepy", line 11, in <module>
    load_entry_point('awsume==3.2.9', 'console_scripts', 'awsumepy')()
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/awsume/awsumepy.py", line 1702, in main
    awsume.run(command_line_arguments)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/awsume/awsumepy.py", line 1666, in run
    mix_role_and_source_profiles(profiles)
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/awsume/awsumepy.py", line 291, in mix_role_and_source_profiles
    merge_role_and_source_profile(profiles[profile], profiles[source_profile_name])
  File "/var/lib/jenkins/.local/lib/python2.7/site-packages/awsume/awsumepy.py", line 262, in merge_role_and_source_profile
    role_profile['aws_access_key_id'] = source_profile['aws_access_key_id']
KeyError: 'aws_access_key_id'
```

Not sure, why it isn't able to find "aws_access_key_id" key in role_profile. The credentials and config files are fine and aws-cli works on the box

**Comment by mbarneyjr** [comment]
It looks like you're using awsume==3.2.9, please try upgrading to version 4 (requires Python 3.5+)

As for the current issue, there must be a profile with a `source_profile` that points to another profile that does not have an `aws_access_key_id` defined

If the issue persists after upgrading, feel free to re-open!

**Comment by varun1231** [comment]
@mbarneyjr Yes, that's correct. I have upgraded to version 4 but the functionality to refer to a nested profile still doesn't exist (except that the concise error is spelt out this time). Is there a plan to add this functionality. We are using "nested" source profile..

**Comment by mbarneyjr** [comment]
I'm not sure what you mean when you say "nested source profile."

There is already functionality to support a role profile, which defines a`source_profile` that will be used as the source credentials when making the assume-role call, is that what you're referring to?

**Comment by varun1231** [comment]
There is your previous comment  `there must be a profile with a source_profile that points to another profile` - this is what I mean by "nested source profile".

**Comment by varun1231** [comment]
@mbarneyjr Any idea when this feature will be implemented?

**Comment by mbarneyjr** [comment]
I have no official roadmap for when features will be implemented, I usually work on awsume in my free time
