### ISSUE TITLE
U2F Support

### ISSUE THREAD

**Issue by mancuss** [trek10inc/awsume#84]
Since AWS Console now supports U2F, it would be good to have that with AWSUME, if at all possible.

**Comment by trek10-mnorris** [comment]
> Since AWS Console now supports U2F, it would be good to have that with AWSUME, if at all possible.

I don't believe this is possible since U2F is only supported in the console at this time (not CLI)

**Comment by gesellix** [comment]
> U2F is only supported in the console at this time (not CLI)

Indeed, see https://github.com/aws/aws-cli/issues/3607.
