### ISSUE TITLE
Installation fails refferencing outdated pip packages

### ISSUE THREAD

**Issue by airmonitor** [trek10inc/awsume#87]
Hello.

I'm using recent botocore, click, six, etc, and apparently only one, specific version of each package has been added to the requirements.

ERROR: awscli 1.16.190 has requirement botocore==1.12.180, but you'll have botocore 1.12.253 which is incompatible.
ERROR: aws-sam-cli 0.19.0 has requirement click~=6.7, but you'll have click 7.0 which is incompatible.
ERROR: aws-sam-cli 0.19.0 has requirement six~=1.11.0, but you'll have six 1.12.0 which is incompatible.

Is there a possibility to update requirements to use more recent version of pip packages?

**Comment by mbarneyjr** [comment]
You can see in the setup file that there is no version requirement for any dependency:
https://github.com/trek10inc/awsume/blob/master/setup.py

To avoid problems like this, we strongly recommend using pipx to isolate your global cli tools, so dependency issues like this do not happen:
https://pipxproject.github.io/pipx/
