### ISSUE TITLE
autocomplete does not work with zsh

### ISSUE THREAD

**Issue by joelgrimberg** [trek10inc/awsume#90]
on a clean machine with oh-my-zsh installed, I installed awsume.
awsume'ing works, except the default awsume autocomplete:
using the tab -key does not give me the options I get when I do a awsume -l .
when I awsume <tab> , I just get the files / folders of my current directory

**Comment by mbarneyjr** [comment]
There must have been an issue with placing the autocomplete script in the right file. You can use the `awsume-configure` utility to set this up after installation, more information found [here](https://awsu.me/utilities/awsume-configure.html)
