### ISSUE TITLE
return: can only `return' from a function or sourced script

### ISSUE THREAD

**Issue by jthomerson** [trek10inc/awsume#99]
Every time I run `awsume -u` I get the error shown below.

```
jrthomerson@mine ~
$ awsume -u
/usr/local/bin/awsume: line 71: return: can only `return' from a function or sourced script
```

**Comment by jthomerson** [comment]
🤦 never mind ... I thought my alias was set up, but it wasn't. It's weird - I did `pip install awsume` and no alias was installed in `~/.bash_profile` or `~/.bashrc`

**Comment by mbarneyjr** [comment]
Hey, glad it was figured out! Would you be willing to submit a PR to include this in the [troubleshooting](https://github.com/trek10inc/awsume/blob/master/docs/troubleshooting/index.md) section of the docs, in case anyone else runs into similar issues and stumbles on the docs [here](https://awsu.me/troubleshooting/)
